services:
  database:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=nagmani
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 1s
      timeout: 10s
      retries: 10 

  backend:
    container_name: backend
    build:
      context: ../
      dockerfile: docker/backend/Dockerfile
    environment:
      - DATABASE_URL=postgresql://postgres:nagmani@database:5432/postgres
    env_file:
      - ../apps/backend/.env
      - ../packages/email/.env
    ports:
      - 3001:3001
    depends_on:
      database:
        condition: service_healthy
    healthcheck:
      test: ["CMD","wget","--spider","-q","http://localhost:3001/health"]
      interval: 1s
      timeout: 10s
      retries: 10

  web:
    container_name: web

    build:
      context: ../
      dockerfile: docker/web/Dockerfile

    ports:
      - 3000:3000

    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://localhost:3001
      - NEXT_PUBLIC_BACKEND_URL=http://backend:3001

    depends_on:
      backend:
        condition: service_healthy

